---
title: "Figure2_largeScaleClustering"
author: "Fabienne Rössler"
date: '2023-03-21'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning = FALSE}
source("../DLCAnalyzer_Functions_v4.R")
source("../UnsupervisedAnalysis_Functions.R")
library(sp)         #tested with v1.3-2
library(imputeTS)   #tested with v2.7
library(ggplot2)    #tested with v3.1.0
library(ggmap)      #tested with v3.0.0
library(data.table) #tested with v1.12.8
library(cowplot)    #tested with v0.9.4
library(corrplot)   #tested with v0.84
library(keras)      #REQUIRES TENSORFLOW INSTALL. tested with v2.2.5.0
library(readr)
library(tidyr)
library(biganalytics)
library(M3C)
library(stringr)
library(reticulate)
set.seed(123)
```

# Figure 2

```{r}
US <- readRDS("../../data/US_AllData_25Clusters.rds")
```

```{r}
US1 <- SplitUSData(US, select = US$meta$Session %in% c("PostCSI"))
US1 <- TwoGroupAnalysis(US1,group = US1$meta$Condition, lab = "kmeans.25")

US2 <- SplitUSData(US, select = US$meta$Session %in% c("FST45min"))
US2 <- TwoGroupAnalysis(US2,group = US2$meta$Treatment, lab = "kmeans.25")

US2_24h <- SplitUSData(US, select = US$meta$Session %in% c("FST24h"))
US2_24h <- TwoGroupAnalysis(US2_24h,group = US2_24h$meta$Treatment, lab = "kmeans.25")

US3 <- SplitUSData(US, select = US$meta$Session == "PostYoh" & US$meta$Condition == "Control")
US3 <- TwoGroupAnalysis(US3,group = US3$meta$Treatment, lab = "kmeans.25")
```


## Barplots showing cluster occurence for CSI, AS and Yohimbine

### CSI

```{r, fig.height=2, fig.width=5.4}
pdat <- US1$Report$kmeans.25
pdat <- data.frame(filename = rownames(pdat),pdat)
pdat <- gather(pdat,key = "key",value = "value", -filename)
pdat$value[is.na(pdat$value)] <- 0
pdat$type <- unlist(lapply(pdat$key,FUN = function(x){strsplit(x, split = "\\.")[[1]][2]}))
pdat$Cluster <- unlist(lapply(pdat$key,FUN = function(x){strsplit(x, split = "\\.")[[1]][1]}))
pdat$Cluster <- as.integer(unlist(lapply(pdat$Cluster,FUN = function(x){strsplit(x, split = "X")[[1]][2]})))
assign <- match(pdat$filename, US1$meta$filename)
pdat$Group <- US1$meta$Condition[assign]
pdat$value <- ifelse(pdat$type == "nframes",pdat$value / 25, pdat$value)
pdat$type[pdat$type == "nframes"] <- "time"
pdat <- pdat[pdat$type == "count",]
df <- aggregate(pdat$value,by = list(pdat$Cluster, pdat$type, pdat$Group), FUN = mean)
colnames(df) <- c("Cluster","type","Group","Mean")
df$SEM <- aggregate(pdat$value,by = list(pdat$Cluster, pdat$type, pdat$Group), FUN = sd)$x / sqrt(30)


p1 <- ggplot(df, aes(x=Cluster, y=Mean, fill=Group, width = 0.75)) + 
  geom_bar(stat="identity", color="black", 
           position=position_dodge()) +
  scale_fill_manual(values = c("white","#0072B2")) +
  geom_errorbar(aes(ymin=Mean-SEM, ymax=Mean+SEM), width=.2,
                position=position_dodge(.8)) +
  #geom_point(data = pdat, aes(Cluster, value, color = Group), position = position_jitterdodge(.3), color = "black", alpha = 0.2, size = 0.3)+ 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), axis.line = element_line(colour = "black")) + 
  scale_x_continuous(breaks = c(1:25)) +
  facet_wrap(~type, ncol = 1,scales = "free")

print(p1)

pdf("../../Plots/Figure2_barplot_CSI.pdf", height = 2, width = 5.4)
print(p1)
dev.off()

US1$Results[[1]]$Statistics$kmeans.25

cluster_stats <- US1$Results[[1]]$Statistics$kmeans.25
cluster_stats_updated <- cluster_stats[grep("count", cluster_stats$name), ]
cluster_stats_updated$FDR <- p.adjust(cluster_stats_updated$p, method = "BY")
cluster_stats_updated
```

### AS 45 min

```{r, fig.height=2, fig.width=5.4}
pdat <- US2$Report$kmeans.25
pdat <- data.frame(filename = rownames(pdat),pdat)
pdat <- gather(pdat,key = "key",value = "value", -filename)
pdat$value[is.na(pdat$value)] <- 0
pdat$type <- unlist(lapply(pdat$key,FUN = function(x){strsplit(x, split = "\\.")[[1]][2]}))
pdat$Cluster <- unlist(lapply(pdat$key,FUN = function(x){strsplit(x, split = "\\.")[[1]][1]}))
pdat$Cluster <- as.integer(unlist(lapply(pdat$Cluster,FUN = function(x){strsplit(x, split = "X")[[1]][2]})))
assign <- match(pdat$filename, US2$meta$filename)
pdat$Group <- US2$meta$Treatment[assign]
pdat$value <- ifelse(pdat$type == "nframes",pdat$value / 25, pdat$value)
pdat$type[pdat$type == "nframes"] <- "time"
pdat <- pdat[pdat$type == "count",]
df <- aggregate(pdat$value,by = list(pdat$Cluster, pdat$type, pdat$Group), FUN = mean)
colnames(df) <- c("Cluster","type","Group","Mean")
df$SEM <- aggregate(pdat$value,by = list(pdat$Cluster, pdat$type, pdat$Group), FUN = sd)$x / sqrt(15)


p1 <- ggplot(df, aes(x=Cluster, y=Mean, fill=Group, width = 0.75)) + 
  geom_bar(stat="identity", color="black", 
           position=position_dodge()) +
  scale_fill_manual(values = c("white","#D52800")) +
  geom_errorbar(aes(ymin=Mean-SEM, ymax=Mean+SEM), width=.2,
                position=position_dodge(.8)) +
  #geom_point(data = pdat, aes(Cluster, value, color = Group), position = position_jitterdodge(.3), color = "black", alpha = 0.2, size = 0.3)+ 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), axis.line = element_line(colour = "black")) + 
  scale_x_continuous(breaks = c(1:25)) +
  facet_wrap(~type, ncol = 1,scales = "free")

print(p1)

pdf("../../Plots/Figure2_barplot_FST45min.pdf", height = 2, width = 5.4)
print(p1)
dev.off()

US2$Results[[1]]$Statistics$kmeans.25

cluster_stats <- US2$Results[[1]]$Statistics$kmeans.25
cluster_stats_updated <- cluster_stats[grep("count", cluster_stats$name), ]
cluster_stats_updated$FDR <- p.adjust(cluster_stats_updated$p, method = "BY")
cluster_stats_updated
```

### Yohimbine

```{r, fig.height=2, fig.width=5.4}
pdat <- US3$Report$kmeans.25
pdat <- data.frame(filename = rownames(pdat),pdat)
pdat <- gather(pdat,key = "key",value = "value", -filename)
pdat$value[is.na(pdat$value)] <- 0
pdat$type <- unlist(lapply(pdat$key,FUN = function(x){strsplit(x, split = "\\.")[[1]][2]}))
pdat$Cluster <- unlist(lapply(pdat$key,FUN = function(x){strsplit(x, split = "\\.")[[1]][1]}))
pdat$Cluster <- as.integer(unlist(lapply(pdat$Cluster,FUN = function(x){strsplit(x, split = "X")[[1]][2]})))
assign <- match(pdat$filename, US3$meta$filename)
pdat$Group <- US3$meta$Treatment[assign]
pdat$value <- ifelse(pdat$type == "nframes",pdat$value / 25, pdat$value)
pdat$type[pdat$type == "nframes"] <- "time"
pdat <- pdat[pdat$type == "count",]
df <- aggregate(pdat$value,by = list(pdat$Cluster, pdat$type, pdat$Group), FUN = mean)
colnames(df) <- c("Cluster","type","Group","Mean")
df$SEM <- aggregate(pdat$value,by = list(pdat$Cluster, pdat$type, pdat$Group), FUN = sd)$x / sqrt(15)

pdat_temp <- pdat[pdat$Group == "Saline", ]
df$SEM[df$Group=="Saline"] <- aggregate(pdat_temp$value,by = list(pdat_temp$Cluster, pdat_temp$type, pdat_temp$Group), FUN = sd)$x / sqrt(5)

p1 <- ggplot(df, aes(x=Cluster, y=Mean, fill=Group, width = 0.75)) + 
  geom_bar(stat="identity", color="black", 
           position=position_dodge()) +
  scale_fill_manual(values = c("white","#CC79A7")) +
  geom_errorbar(aes(ymin=Mean-SEM, ymax=Mean+SEM), width=.2,
                position=position_dodge(.8)) +
  #geom_point(data = pdat, aes(Cluster, value, color = Group), position = position_jitterdodge(.3), color = "black", alpha = 0.2, size = 0.3)+ 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), axis.line = element_line(colour = "black")) + 
  scale_x_continuous(breaks = c(1:25)) +
  facet_wrap(~type, ncol = 1,scales = "free")

print(p1)

pdf("../../Plots/Figure2_barplot_yohimbine.pdf", height = 2, width = 5.4)
print(p1)
dev.off()

US3$Results[[1]]$Statistics$kmeans.25

cluster_stats <- US3$Results[[1]]$Statistics$kmeans.25
cluster_stats_updated <- cluster_stats[grep("count", cluster_stats$name), ]
cluster_stats_updated$FDR <- p.adjust(cluster_stats_updated$p, method = "BY")
cluster_stats_updated
```

## Behavior flow differences for CSI, AS and Yohimbine

### CSI

```{r, fig.height=5, fig.width=5}
PlotBehaviorFlow_Delta(US1, grouping = US1$meta$Condition == "CSI", lab = "kmeans.25")

US1$Results[[1]]$TransitionStats$kmeans.25

trans_stats <- US1$Results[[1]]$TransitionStats$kmeans.25$transitions
trans_stats_updated <- tidyr::drop_na(trans_stats, "p.value")
trans_stats_updated$FDR <- p.adjust(trans_stats_updated$p.value, method = "BY")
trans_stats_updated

pdf("../../Plots/Figure2_CSI_behaviorFlowDelta.pdf", height = 5, width = 5)
PlotBehaviorFlow_Delta(US1, grouping = US1$meta$Condition == "CSI", lab = "kmeans.25")
dev.off()
```

### AS 45 min

```{r, fig.height=5, fig.width=5}
PlotBehaviorFlow_Delta(US2, grouping = US2$meta$Treatment == "Swim", lab = "kmeans.25")

US2$Results$`Swim-vs-Control`$TransitionStats$kmeans.25

trans_stats <- US2$Results[[1]]$TransitionStats$kmeans.25$transitions
trans_stats_updated <- tidyr::drop_na(trans_stats, "p.value")
trans_stats_updated$FDR <- p.adjust(trans_stats_updated$p.value, method = "BY")
trans_stats_updated

pdf("../../Plots/Figure2_AS45min_behaviorFlowDelta.pdf", height = 5, width = 5)
PlotBehaviorFlow_Delta(US2, grouping = US2$meta$Treatment == "Swim", lab = "kmeans.25")
dev.off()
```

### Yohimbine

```{r, fig.height=5, fig.width=5}
PlotBehaviorFlow_Delta(US3, grouping = US3$meta$Treatment == "Yohimbin", lab = "kmeans.25")

US3$Results[[1]]$TransitionStats$kmeans.25

trans_stats <- US3$Results[[1]]$TransitionStats$kmeans.25$transitions
trans_stats_updated <- tidyr::drop_na(trans_stats, "p.value")
trans_stats_updated$FDR <- p.adjust(trans_stats_updated$p.value, method = "BY")
trans_stats_updated

pdf("../../Plots/Figure2_Yohimbine_behaviorFlowDelta.pdf", height = 5, width = 5)
PlotBehaviorFlow_Delta(US3, grouping = US3$meta$Treatment == "Yohimbin", lab = "kmeans.25")
dev.off()
```

## BFA for CSI, AS and Yohimbine

### CSI

```{r, fig.width=5, fig.height=2.5}
PlotTransitionsStats(US1, labels = "kmeans.25")

pdf("../../Plots/Figure2_bootstrapping_CSI.pdf", height = 2.5, width = 5)
PlotTransitionsStats(US1, labels = "kmeans.25")
dev.off()
```

### AS 45 min

```{r, fig.width=5, fig.height=1.5}
PlotTransitionsStats(US2, labels = "kmeans.25")

pdf("../../Plots/Figure2_bootstrapping_AS45min.pdf", height = 1.5, width = 5)
PlotTransitionsStats(US2, labels = "kmeans.25")
dev.off()
```

## AS 24 hours

```{r, fig.width= 5, fig.height=1.5}
PlotTransitionsStats(US2_24h, labels = "kmeans.25")

pdf("../../Plots/Figure2_bootstrapping_AS24h.pdf", height = 1.5, width = 5)
PlotTransitionsStats(US2_24h, labels = "kmeans.25")
dev.off()
```

### Yohimbine

```{r, fig.width= 5, fig.height=2.5}
PlotTransitionsStats(US3, labels = "kmeans.25")

pdf("../../Plots/Figure2_bootstrapping_yohimbine.pdf", height = 2.5, width = 5)
PlotTransitionsStats(US3, labels = "kmeans.25")
dev.off()
```


## Sensitivity curves for CSI, AS and Yohimbine

### CSI

```{r,fig.width= 3.5, fig.height=2}
dat <- readRDS("../../data/CSI_Sensitivity_25Clusters_50sim.rds")

#-log 10 transform statistical values
dat[,-c(1:2)] <- -log10(dat[,-c(1:2)])

#aggregate mean and sd
means <- aggregate(dat, FUN = mean, by = list(dat$n_animals))
sds <- aggregate(dat, FUN = sd, by = list(dat$n_animals))
means <- means[,-c(2:3)]
sds <- sds[,-c(2:3)]

gs <- means$Group.1 / 2
means <- gather(means, key = "Group.1", value = "p.value")
means$GroupSize <- rep(gs,ncol(dat) - 2)
sds <- gather(sds, key = "Group.1", value = "sd")
means$sem <- gather(sds, key = "Group.1", value = "sd")$sd / sqrt(max(dat$n_sim))

#means <- means[means$GroupSize != 25,]
means$Type <- "Classical"
means$Type[grepl("kmeans.",means$Group.1)] <- "kmeans"


p1 <- ggplot(means[means$Group.1 %in% c("kmeans.25.matstats.p","classical.top.p","DLC.PCA.LogReg.p", "DLC.PCA.p"),], aes(GroupSize,p.value, color = Group.1)) + 
  geom_ribbon(aes(ymin = p.value-sem,ymax = p.value+sem, fill = Group.1,alpha = 0.1)) + 
  geom_line(size = 1) +
  scale_x_reverse(breaks = c(25, 20, 15, 10, 5)) + 
  ylim(0.3, 8.3) +
  scale_color_manual(values = c("grey","blue","black","#994F88")) +
  scale_fill_manual(values = c("grey","blue","black","#994F88")) +
  #geom_hline(yintercept = -log10(0.05), color = "red") +
  theme_bw() + ylab("-log10(p-value)") + xlab("group size") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), axis.line = element_line(colour = "black"))


print(p1)

pdf("../../Plots/Figure2_sensitivity_CSI.pdf", height = 2, width = 3.5)
print(p1)
dev.off()
```

### AS 45 min

```{r,fig.width= 3.5, fig.height=2}
dat <- readRDS("../../data/AS45min_Sensitivity_25Clusters_50sim.rds")

#-log 10 transform statistical values
dat[,-c(1:2)] <- -log10(dat[,-c(1:2)])

#aggregate mean and sd
means <- aggregate(dat, FUN = mean, by = list(dat$n_animals), na.rm = TRUE)
sds <- aggregate(dat, FUN = sd, by = list(dat$n_animals), na.rm = TRUE)
means <- means[,-c(2:3)]
sds <- sds[,-c(2:3)]

gs <- means$Group.1 / 2
means <- gather(means, key = "Group.1", value = "p.value")
means$GroupSize <- rep(gs,ncol(dat) - 2)
sds <- gather(sds, key = "Group.1", value = "sd")
means$sem <- gather(sds, key = "Group.1", value = "sd")$sd / sqrt(max(dat$n_sim))

#means <- means[means$GroupSize != 25,]
means$Type <- "Classical"
means$Type[grepl("kmeans.",means$Group.1)] <- "kmeans"


p1 <- ggplot(means[means$Group.1 %in% c("kmeans.25.matstats.p","classical.top.p","DLC.PCA.LogReg.p", "DLC.PCA.p"),], aes(GroupSize,p.value, color = Group.1)) + 
  geom_ribbon(aes(ymin = p.value-sem,ymax = p.value+sem, fill = Group.1,alpha = 0.1)) + 
  geom_line(size = 1) +
  scale_x_reverse(breaks = c(13, 11, 9, 7, 5)) + 
  #ylim(0.3, 8.3) +
  scale_color_manual(values = c("grey","blue","black","#994F88")) +
  scale_fill_manual(values = c("grey","blue", "black","#994F88")) +
  #geom_hline(yintercept = -log10(0.05), color = "red") +
  theme_bw() + ylab("-log10(p-value)") + xlab("group size") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), axis.line = element_line(colour = "black"))


print(p1)

pdf("../../Plots/Figure2_sensitivity_FST45min.pdf", height = 2, width = 3.5)
print(p1)
dev.off()
```

### AS 24 hours

```{r,fig.width= 3.5, fig.height=2}
dat <- readRDS("../../data/AS24h_Sensitivity_25Clusters_50sim.rds")

#-log 10 transform statistical values
dat[,-c(1:2)] <- -log10(dat[,-c(1:2)])

#aggregate mean and sd
means <- aggregate(dat, FUN = mean, by = list(dat$n_animals))
sds <- aggregate(dat, FUN = sd, by = list(dat$n_animals))
means <- means[,-c(2:3)]
sds <- sds[,-c(2:3)]

gs <- means$Group.1 / 2
means <- gather(means, key = "Group.1", value = "p.value")
means$GroupSize <- rep(gs,ncol(dat) - 2)
sds <- gather(sds, key = "Group.1", value = "sd")
means$sem <- gather(sds, key = "Group.1", value = "sd")$sd / sqrt(max(dat$n_sim))

#means <- means[means$GroupSize != 25,]
means$Type <- "Classical"
means$Type[grepl("kmeans.",means$Group.1)] <- "kmeans"

p1 <- ggplot(means[means$Group.1 %in% c("kmeans.25.matstats.p","classical.top.p","DLC.PCA.LogReg.p","DLC.PCA.p"),], aes(GroupSize,p.value, color = Group.1)) + 
  geom_ribbon(aes(ymin = p.value-sem,ymax = p.value+sem, fill = Group.1,alpha = 0.1)) + 
  geom_line(size = 1) +
  scale_x_reverse(breaks = c(13, 11, 9, 7, 5)) + 
  #ylim(0.3, 8.3) +
  scale_color_manual(values = c("grey","blue","black","#994F88")) +
  scale_fill_manual(values = c("grey","blue","black","#994F88")) +
  #geom_hline(yintercept = -log10(0.05), color = "red") +
  theme_bw() + ylab("-log10(p-value)") + xlab("group size") + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), axis.line = element_line(colour = "black"))

print(p1)

pdf("../../Plots/Figure2_sensitivity_FST24h.pdf", height = 2, width = 3.5)
print(p1)
dev.off()
```


