---
title: "SupplFig_VAME_80Clusters"
author: "Fabienne Rössler"
date: '2023-03-01'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning = FALSE}
source("../DLCAnalyzer_Functions_v4.R")
source("../UnsupervisedAnalysis_Functions.R")
library(sp)         #tested with v1.3-2
library(imputeTS)   #tested with v2.7
library(ggplot2)    #tested with v3.1.0
library(ggmap)      #tested with v3.0.0
library(data.table) #tested with v1.12.8
library(cowplot)    #tested with v0.9.4
library(corrplot)   #tested with v0.84
library(keras)      #REQUIRES TENSORFLOW INSTALL. tested with v2.2.5.0
library(readr)
library(tidyr)
library(biganalytics)
library(M3C)
library(stringr)
library(reticulate)
set.seed(123)
```

# Suppl. Figure for VAME (80 clusters)

```{r}
US <- readRDS("../../data/US_ComparisonClustering_CSI_processed.rds")
```

## Decision about number of clusters

```{r, eval = FALSE}
np <- import("numpy")

path <- "../../data/VAME_clustering/100_Clusters/"
list_files <- grep(pattern = "100_km",list.files(path, full.names = TRUE),value = TRUE)
VAME_clusters <- list()
for (i in list_files){
  mat <- np$load(i)
  VAME_clusters[[i]] <- mat
}

list_files <- names(VAME_clusters)

# Count occurrences of each cluster in each file
clusters_100 <- matrix(0, length(list_files), 100)
c <- 1
for (lf in list_files) {
  curr_file <- VAME_clusters[[lf]]
  for (i in 1:100) {
    counts_cluster <- length(which(curr_file == i))
    clusters_100[c, i] <- counts_cluster
  }
  c <- c+1
}

# Compute proportions
row_sum <- rowSums(clusters_100)
clusters_100_prop <- clusters_100/row_sum

# Sort proportions from highest to lowest for each file
for (i in 1:nrow(clusters_100_prop)) {
  clusters_100_prop[i, ] <- sort(clusters_100_prop[i, ], decreasing = TRUE)
}

# Calculate mean proportions over all files 
mean_prop <- colMeans(clusters_100_prop)
sem_prop <- apply(clusters_100_prop, MARGIN = 2, function(x) sd(x)/sqrt(length(x)))

# Add up proportions
sum_prop <- clusters_100_prop
for (i in 1:nrow(clusters_100_prop))
  for (j in 2:ncol(clusters_100_prop))
    sum_prop[i, j] <- rowSums(clusters_100_prop[i, 1:j, drop = FALSE])

# Calculate mean sum of proportions over all files 
mean_sum_prop <- colMeans(sum_prop)
sem_sum_prop <- apply(sum_prop,  MARGIN = 2, function(x) sd(x)/sqrt(length(x)))
```

Plotting the results.

```{r, fig.height=2.5, fig.width=4}
min_clust <- which(mean_sum_prop > 0.95)[1]

df2 <- data.frame(1:100, mean_sum_prop, sem_sum_prop)

p1 <- ggplot(df2, aes(x=X1.100,y=mean_sum_prop)) + 
  geom_ribbon(aes(ymin = mean_sum_prop-sem_sum_prop,ymax = mean_sum_prop+sem_sum_prop,alpha = 0.1)) + 
  geom_line() +
  scale_color_manual(values = "black") +
  scale_fill_manual(values = "grey") +
  theme_bw() + ylab("Additive cluster proportion") + xlab("Sorted clusters") +
  geom_hline(yintercept = 0.95, linetype='dotted', color = "red") + geom_vline(xintercept = min_clust, linetype='dotted', color = "red") +
  theme(legend.position="none") + geom_vline(xintercept = 80, linetype='dashed', color = "blue") +
  scale_x_continuous(breaks = seq(0, 100, by=20))

print(p1)

pdf("../../Plots/SupplFigure_VAME80_additiveClusterProps.pdf", height = 2.5, width = 4)
print(p1)
dev.off()
```

## Barplot for occurence of different clusters

```{r, fig.height=1.5, fig.width=11}
pdat <- US$Report$VAME.80
pdat <- data.frame(filename = rownames(pdat),pdat)
pdat <- gather(pdat,key = "key",value = "value", -filename)
pdat$value[is.na(pdat$value)] <- 0
pdat$type <- unlist(lapply(pdat$key,FUN = function(x){strsplit(x, split = "\\.")[[1]][2]}))
pdat$Cluster <- unlist(lapply(pdat$key,FUN = function(x){strsplit(x, split = "\\.")[[1]][1]}))
pdat$Cluster <- as.integer(unlist(lapply(pdat$Cluster,FUN = function(x){strsplit(x, split = "X")[[1]][2]})))
assign <- match(pdat$filename, US$meta$filename)
pdat$Group <- US$meta$Condition[assign]
pdat$value <- ifelse(pdat$type == "nframes",pdat$value / 25, pdat$value)
pdat$type[pdat$type == "nframes"] <- "time"
pdat <- pdat[pdat$type == "count",]
df <- aggregate(pdat$value,by = list(pdat$Cluster, pdat$type, pdat$Group), FUN = mean)
colnames(df) <- c("Cluster","type","Group","Mean")
df$SEM <- aggregate(pdat$value,by = list(pdat$Cluster, pdat$type, pdat$Group), FUN = sd)$x / sqrt(30)


p1 <- ggplot(df, aes(x=Cluster, y=Mean, fill=Group, width = 0.75)) + 
  geom_bar(stat="identity", color="black", 
           position=position_dodge()) +
  scale_fill_manual(values = c("white","#0072B2")) +
  geom_errorbar(aes(ymin=Mean-SEM, ymax=Mean+SEM), width=.2,
                position=position_dodge(.8)) +
  #geom_point(data = pdat, aes(Cluster, value, color = Group), position = position_jitterdodge(.3), color = "black", alpha = 0.2, size = 0.3)+ 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), axis.line = element_line(colour = "black")) + 
  scale_x_continuous(breaks = c(0:79)) +
  facet_wrap(~type, ncol = 1,scales = "free")

print(p1)

pdf("../../Plots/SupplFigure_VAME80_barplot.pdf", height = 1.5, width = 11)
print(p1)
dev.off()

US$Results[[1]]$Statistics$VAME.80

cluster_stats <- US$Results[[1]]$Statistics$VAME.80
cluster_stats_updated <- cluster_stats[grep("count", cluster_stats$name), ]
cluster_stats_updated$FDR <- p.adjust(cluster_stats_updated$p, method = "BY")
cluster_stats_updated
```


## Mapping from kmeans to VAME

```{r, fig.height=8.5, fig.width=8.5}
PlotConfusionMatrix(US$ConfusionMatrix_norm$`kmeans.70_CSI-VAME.80`,pointsize = 4, hclust = TRUE)

pdf("../../Plots/SupplFigure_VAME80_confusionKmeans.pdf", height = 8.5, width = 8.5)
PlotConfusionMatrix(US$ConfusionMatrix_norm$`kmeans.70_CSI-VAME.80`,pointsize = 4, hclust = TRUE)
dev.off()
```


## Circle plots for transitions between clusters

```{r, fig.height=5, fig.width=5}
PlotBehaviorFlow(US,lab = "VAME.80")

pdf("../../Plots/SupplFig_VAME80_circlePlot.pdf", height = 5, width = 5)
PlotBehaviorFlow(US,lab = "VAME.80")
dev.off()
```

Plot change in transitions between clusters:

```{r, fig.height=5, fig.width=5}
PlotBehaviorFlow_Delta(US, US$meta$Condition == "CSI", lab = "VAME.80")

pdf("../../Plots/SupplFig_VAME80_circlePlot_delta.pdf", height = 5, width = 5)
PlotBehaviorFlow_Delta(US, US$meta$Condition == "CSI", lab = "VAME.80")
dev.off()

#clusters Transition Stats
head(US$Results[[1]]$TransitionStats$VAME.80)

trans_stats <- US$Results[[1]]$TransitionStats$VAME.80$transitions
trans_stats_updated <- tidyr::drop_na(trans_stats, "p.value")
trans_stats_updated$FDR <- p.adjust(trans_stats_updated$p.value, method = "BY")
```

## Results of bootstrapping analysis

```{r, fig.width= 5, fig.height=1.5}
PlotTransitionsStats(US, labels = "VAME.80")

pdf("../../Plots/SupplFigure_bootstrapping_VAME80.pdf", height = 1.5, width = 5)
PlotTransitionsStats(US, labels = "VAME.80")
dev.off()
```

