---
title: "SupplFigure_Yohimbine_Roche"
author: "Fabienne Rössler"
date: '2023-06-08'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning = FALSE}
source("../DLCAnalyzer_Functions_v4.R")
source("../UnsupervisedAnalysis_Functions.R")
library(rlang)
library(sp)         #tested with v1.3-2
library(imputeTS)   #tested with v2.7
library(ggplot2)    #tested with v3.1.0
library(ggmap)      #tested with v3.0.0
library(data.table) #tested with v1.12.8
library(cowplot)    #tested with v0.9.4
library(corrplot)   #tested with v0.84
library(keras)      #REQUIRES TENSORFLOW INSTALL. tested with v2.2.5.0
library(readr)
library(tidyr)
library(biganalytics)
library(M3C)
library(stringr)
library(reticulate)
library(pROC)
library(yardstick)
set.seed(123)
```

# Supplementary Figure for yohimbine experiment from Roche

```{r}
US <- readRDS("../../data/US_YohimbineRoche_25Clusters_processed.rds")
US <- TwoGroupAnalysis(US,group = US$meta$Group, lab = "kmeans.25_YohRoche")
```


## Barplot for occurence of different clusters

```{r, fig.height=2.5, fig.width=11}
pdat <- US$Report$kmeans.25_YohRoche
pdat <- data.frame(filename = rownames(pdat),pdat)
pdat <- gather(pdat,key = "key",value = "value", -filename)
pdat$value[is.na(pdat$value)] <- 0
pdat$type <- unlist(lapply(pdat$key,FUN = function(x){strsplit(x, split = "\\.")[[1]][2]}))
pdat$Cluster <- unlist(lapply(pdat$key,FUN = function(x){strsplit(x, split = "\\.")[[1]][1]}))
pdat$Cluster <- as.integer(unlist(lapply(pdat$Cluster,FUN = function(x){strsplit(x, split = "X")[[1]][2]})))
assign <- match(pdat$filename, US$meta$filename)
pdat$Group <- US$meta$Group[assign]
pdat$value <- ifelse(pdat$type == "nframes",pdat$value / 25, pdat$value)
pdat$type[pdat$type == "nframes"] <- "time"
pdat <- pdat[pdat$type == "count",]
df <- aggregate(pdat$value,by = list(pdat$Cluster, pdat$type, pdat$Group), FUN = mean)
colnames(df) <- c("Cluster","type","Group","Mean")
df$SEM <- aggregate(pdat$value,by = list(pdat$Cluster, pdat$type, pdat$Group), FUN = sd)$x / sqrt(24)

pdat_temp <- pdat[pdat$Group == "Control", ]
df$SEM[df$Group=="Control"] <- aggregate(pdat_temp$value,by = list(pdat_temp$Cluster, pdat_temp$type, pdat_temp$Group), FUN = sd)$x / sqrt(8)

p1 <- ggplot(df, aes(x=Cluster, y=Mean, fill=Group, width = 0.75)) + 
  geom_bar(stat="identity", color="black", 
           position=position_dodge()) +
  scale_fill_manual(values = c("white","#8B3564")) +
  geom_errorbar(aes(ymin=Mean-SEM, ymax=Mean+SEM), width=.2,
                position=position_dodge(.8)) +
  #geom_point(data = pdat, aes(Cluster, value, color = Group), position = position_jitterdodge(.3), color = "black", alpha = 0.2, size = 0.3)+ 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), axis.line = element_line(colour = "black")) + 
  scale_x_continuous(breaks = c(1:25)) +
  facet_wrap(~type, ncol = 1,scales = "free")

print(p1)

pdf("../../Plots/SupplFigure_YoimbineRoche_barplot.pdf", height = 2.5, width = 11)
print(p1)
dev.off()

US$Results[[1]]$Statistics$kmeans.25_YohRoche

cluster_stats <- US$Results[[1]]$Statistics$kmeans.25_YohRoche
cluster_stats_updated <- cluster_stats[grep("count", cluster_stats$name), ]
cluster_stats_updated$FDR <- p.adjust(cluster_stats_updated$p, method = "BY")
cluster_stats_updated
```


## BFA computed for different dosages

### 1 mg/kg vs. control

```{r}
US1 <- SplitUSData(US, select = US$meta$Dosage %in% c("0", "1"))
set.seed(123)
US1 <- TwoGroupAnalysis(US1,group = US1$meta$Group)
```

```{r, fig.height=1.8, fig.width=3.5}
PlotTransitionsStats(US1, labels = "kmeans.25_YohRoche")

pdf("../../Plots/SupplFigure_YoimbineRoche_BFA_1mgkg.pdf", height = 1.8, width = 3.5)
PlotTransitionsStats(US1, labels = "kmeans.25_YohRoche")
dev.off()
```

### 3 mg/kg vs. control

```{r}
US3 <- SplitUSData(US, select = US$meta$Dosage %in% c("0", "3"))
set.seed(123)
US3 <- TwoGroupAnalysis(US3,group = US3$meta$Group)
```

```{r, fig.height=1.8, fig.width=3.5}
PlotTransitionsStats(US3, labels = "kmeans.25_YohRoche")

pdf("../../Plots/SupplFigure_YoimbineRoche_BFA_3mgkg.pdf", height = 1.8, width = 3.5)
PlotTransitionsStats(US3, labels = "kmeans.25_YohRoche")
dev.off()
```

### 6 mg/kg vs. control

```{r}
US6 <- SplitUSData(US, select = US$meta$Dosage %in% c("0", "6"))
set.seed(123)
US6 <- TwoGroupAnalysis(US6,group = US6$meta$Group)
```

```{r, fig.height=1.8, fig.width=3.5}
PlotTransitionsStats(US6, labels = "kmeans.25_YohRoche")

pdf("../../Plots/SupplFigure_YoimbineRoche_BFA_6mgkg.pdf", height = 1.8, width = 3.5)
PlotTransitionsStats(US6, labels = "kmeans.25_YohRoche")
dev.off()
```

