---
title: "SupplFigure_kmeans_70Clusters"
author: "Fabienne Rössler"
date: '2023-05-10'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning = FALSE}
source("../DLCAnalyzer_Functions_v4.R")
source("../UnsupervisedAnalysis_Functions.R")
library(sp)         #tested with v1.3-2
library(imputeTS)   #tested with v2.7
library(ggplot2)    #tested with v3.1.0
library(ggmap)      #tested with v3.0.0
library(data.table) #tested with v1.12.8
library(cowplot)    #tested with v0.9.4
library(corrplot)   #tested with v0.84
library(keras)      #REQUIRES TENSORFLOW INSTALL. tested with v2.2.5.0
library(readr)
library(tidyr)
library(biganalytics)
library(M3C)
library(stringr)
library(reticulate)
set.seed(123)
```

# Suppl. Figure for k-means (with 70 clusters)

## Decision on best number of clusters for k-means

```{r}
US2 <- readRDS("../../data/US_100_Clusters.rds")

clusters_100 <- US2$Report$kmeans.100

clusters_100 <- clusters_100[, str_detect(colnames(clusters_100), "nframes")]
clusters_100[is.na(clusters_100)] <- 0

colnames(clusters_100) <- 0

# Compute proportions
row_sum <- rowSums(clusters_100)
clusters_100_prop <- clusters_100/row_sum

# Sort proportions from highest to lowest for each file
for (i in 1:nrow(clusters_100_prop))
  clusters_100_prop[i, ] <- sort(clusters_100_prop[i, ], decreasing = TRUE)

# Calculate mean proportions over all files 
mean_prop <- sapply(clusters_100_prop, mean)
sem_prop <- sapply(clusters_100_prop, function(x)sd(x)/sqrt(length(x)))

# Add up proportions
sum_prop <- clusters_100_prop
for (i in 1:nrow(clusters_100_prop))
  for (j in 2:ncol(clusters_100_prop))
    sum_prop[i, j] <- rowSums(clusters_100_prop[i, 1:j])

# Calculate mean sum of proportions over all files 
mean_sum_prop <- sapply(sum_prop, mean)
sem_sum_prop <- sapply(sum_prop, function(x)sd(x)/sqrt(length(x)))
```

Plotting the results.

```{r, fig.height=2.2, fig.width=3.2}
min_clust <- which(mean_sum_prop > 0.95)[1]

df2 <- data.frame(1:100, mean_sum_prop, sem_sum_prop)

p1 <- ggplot(df2, aes(x=X1.100,y=mean_sum_prop)) + 
  geom_ribbon(aes(ymin = mean_sum_prop-sem_sum_prop,ymax = mean_sum_prop+sem_sum_prop,alpha = 0.1)) + 
  geom_line() +
  scale_color_manual(values = "black") +
  scale_fill_manual(values = "grey") +
  theme_bw() + ylab("Additive cluster proportion") + xlab("Sorted clusters") +
  geom_hline(yintercept = 0.95, linetype='dotted', color = "red") + geom_vline(xintercept = min_clust, linetype='dotted', color = "red") +
  theme(legend.position="none", panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), axis.line = element_line(colour = "black")) + geom_vline(xintercept = 70, linetype='dashed', color = "blue")

print(p1)

pdf("../../Plots/SupplFig_kmeans70_additiveClusterProps.pdf", height = 2.2, width = 3.2)
print(p1)
dev.off()
```


## Sensitivitiy curves for "classical" vs. cluster/transition stats

```{r, fig.width= 3.3, fig.height=2}
dat <- readRDS("../../data/CSI_Sensitivity_50sim_classical.rds")
dat$classical.top.p.nadj <- dat$classical.top.p / 4

#-log 10 transform statistical values
dat[,-c(1:2)] <- -log10(dat[,-c(1:2)])

#aggregate mean and sd
means <- aggregate(dat, FUN = mean, by = list(dat$n_animals))
sds <- aggregate(dat, FUN = sd, by = list(dat$n_animals))
means <- means[,-c(2:3)]
sds <- sds[,-c(2:3)]

gs <- means$Group.1 / 2
means <- gather(means, key = "Group.1", value = "p.value")
means$GroupSize <- rep(gs,ncol(dat) - 2)
sds <- gather(sds, key = "Group.1", value = "sd")
means$sem <- gather(sds, key = "Group.1", value = "sd")$sd / sqrt(max(dat$n_sim))

means$Type <- "Classical"
means$Type[grepl("kmeans.",means$Group.1)] <- "kmeans"
means$Type[grepl("BSOID.",means$Group.1)] <- "BSOID"

p1 <- ggplot(means[means$Group.1 %in% c("kmeans.70.topclust.FDR","kmeans.70.toptrans.FDR","classical.top.p"),], aes(GroupSize,p.value, color = Group.1)) + 
  geom_ribbon(aes(ymin = p.value-sem,ymax = p.value+sem, fill = Group.1,alpha = 0.1)) + 
  geom_line(size = 1) +
  scale_x_reverse() + 
  scale_color_manual(values = c("black","#3A46BF","#C44523")) +
  scale_fill_manual(values = c("black","#3A46BF","#C44523")) +
  #geom_hline(yintercept = -log10(0.05), color = "red") +
  theme_bw() + ylab("-log10(p-value)") + xlab("Group Size") +
  scale_y_continuous(limits = c(0,6)) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), axis.line = element_line(colour = "black"))


p2 <- ggplot(means[means$Group.1 %in% c("kmeans.70.topclust.p","kmeans.70.toptrans.p","classical.top.p.nadj"),], aes(GroupSize,p.value, color = Group.1)) + 
  geom_ribbon(aes(ymin = p.value-sem,ymax = p.value+sem, fill = Group.1,alpha = 0.1)) + 
  geom_line(size = 1) +
  scale_x_reverse() + 
  scale_color_manual(values = c("black","#3A46BF","#C44523")) +
  scale_fill_manual(values = c("black","#3A46BF","#C44523")) +
  #geom_hline(yintercept = -log10(0.05), color = "red") +
  theme_bw() + ylab("-log10(p-value)") + xlab("Group Size") + 
  scale_y_continuous(limits = c(0,6)) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), axis.line = element_line(colour = "black"))

print(p1)
print(p2)


pdf("../../Plots/SupplFig_kmeans70_classicalvsClusters.pdf", height = 2.2, width = 3.75)
print(p1)
dev.off()


pdf("../../Plots/SupplFig_kmeans70_classicalvsClusters_rawP.pdf", height = 2.2, width = 3.6)
print(p2)
dev.off()
```
