---
title: "SupplFig_IFS_FreezingResponse"
author: "Fabienne Rössler"
date: '2023-07-06'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning = FALSE}
source("../DLCAnalyzer_Functions_v4.R")
source("../UnsupervisedAnalysis_Functions.R")
library(rlang)
library(sp)         #tested with v1.3-2
library(imputeTS)   #tested with v2.7
library(ggplot2)    #tested with v3.1.0
library(ggmap)      #tested with v3.0.0
library(data.table) #tested with v1.12.8
library(cowplot)    #tested with v0.9.4
library(corrplot)   #tested with v0.84
library(keras)      #REQUIRES TENSORFLOW INSTALL. tested with v2.2.5.0
library(readr)
library(tidyr)
library(biganalytics)
library(M3C)
library(stringr)
library(reticulate)
library(pROC)
library(yardstick)
set.seed(123)
```

# Suppl Figure to show development of freezing behavior

```{r}
US <- readRDS("../../data/US_IFS_25Clusters_withResilience.rds")

US2 <- SplitUSData(US, select = US$meta$Session %in% c("OFT2"))
```

## Boxplots of freezing behavior over 6 extinction days (grouped by resilience type)

```{r, fig.height=2, fig.width=6}
US2$meta$Ex1 <- as.numeric(gsub(",", ".", US2$meta$Ex1))
US2$meta$Ex2 <- as.numeric(gsub(",", ".", US2$meta$Ex2))
US2$meta$Ex3 <- as.numeric(gsub(",", ".", US2$meta$Ex3))
US2$meta$Ex4 <- as.numeric(gsub(",", ".", US2$meta$Ex4))
US2$meta$Ex5 <- as.numeric(gsub(",", ".", US2$meta$Ex5))
US2$meta$Ex6 <- as.numeric(gsub(",", ".", US2$meta$Ex6))

pdat <- US2$meta

pdat$resilient_ID <- factor(pdat$resilient_ID, levels = c("control", "resilient", "susceptible"))

pdat <- pdat[,c("resilient_ID","Session","animal_ID","Ex1","Ex2","Ex3","Ex4","Ex5","Ex6")]
pdat <- tidyr::gather(pdat,key = "ExtinctionSession",value = "freezing", -resilient_ID, -Session, -animal_ID)

p <- ggplot(pdat[pdat$resilient_ID %in% c("control", "resilient", "susceptible"), ], aes(x = ExtinctionSession,y = freezing, color = resilient_ID)) + 
  geom_boxplot() + 
  facet_wrap(~resilient_ID, ncol = 3) +
  geom_point() + 
  scale_color_manual(values = c("black", "#5D3A9B", "#E66100")) + theme_bw() + 
  labs(y= "freezing %", x = "") + theme(legend.position = "none") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())
p

pdf("../../Plots/SupplFig_IFS_boxplots_extinctionDays1to6.pdf", height = 2, width = 6)
print(p)
dev.off()
```


## Boxplots of freezing behavior (on extinction day 1 and extinction day 6) for grouping by Colucci et al. 

```{r, fig.height=2, fig.width=2.8}
US2_resilience <- SplitUSData(US2, select = US2$meta$resilient_ID %in% c("resilient", "susceptible"))

pdat <- cbind(US2_resilience$Report$raw,US2_resilience$meta)

pdat$new_resilient_bydistance_ID <- "non-responder"
pdat$new_resilient_bydistance_ID[pdat$bodycentre.distance.moving < quantile(pdat$bodycentre.distance.moving)[2]] <- "low responder"
pdat$new_resilient_bydistance_ID[pdat$bodycentre.distance.moving > quantile(pdat$bodycentre.distance.moving)[4]] <- "high responder"

pdat$new_resilient_bydistance_ID <- factor(pdat$new_resilient_bydistance_ID, levels = c("non-responder", "low responder", "high responder"))


p1 <- ggplot(pdat, aes(x = new_resilient_bydistance_ID,y = bodycentre.distance.moving/100, color = new_resilient_bydistance_ID)) + 
  geom_boxplot(outlier.shape = NA) +
  geom_point(position = position_jitter(width = 0.15)) + 
  scale_color_manual(values = c("grey", "#41296D", "#B44D00")) +
  theme_bw() +
  labs(y= "Meters", x = "", title = "Distance") + theme(plot.title = element_text(hjust = 0.5), legend.position = "none") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())
p1


p2 <- ggplot(pdat, aes(x = new_resilient_bydistance_ID,y = Ex1, color = new_resilient_bydistance_ID)) + 
  geom_boxplot(outlier.shape = NA) +
  geom_point(position = position_jitter(width = 0.15)) + 
  scale_color_manual(values = c("grey", "#41296D", "#B44D00")) +
  ylim(10, 80) +
  theme_bw() +
  labs(y= "Freezing %", x = "", title = "Extinction day 1") + theme(plot.title = element_text(hjust = 0.5), legend.position = "none") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())
p2

one_way_anova <- aov(Ex1 ~ new_resilient_bydistance_ID, data = pdat)

summary(one_way_anova)

post_hoc_Tukey <- TukeyHSD(one_way_anova)

post_hoc_Tukey


p3 <- ggplot(pdat, aes(x = new_resilient_bydistance_ID,y = Ex6, color = new_resilient_bydistance_ID)) + 
  #geom_boxplot(outlier.shape = NA, color = "black", fill = c("grey", "#DDCC77", "#5D3A9B")) + 
  geom_boxplot(outlier.shape = NA) +
  geom_point(position = position_jitter(width = 0.15)) + 
  scale_color_manual(values = c("grey", "#41296D", "#B44D00")) +
  ylim(10, 80) +
  theme_bw() +
  labs(y= "Freezing %", x = "", title = "Extinction day 6") + theme(plot.title = element_text(hjust = 0.5), legend.position = "none") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())
p3

one_way_anova <- aov(Ex6 ~ new_resilient_bydistance_ID, data = pdat)

summary(one_way_anova)

post_hoc_Tukey <- TukeyHSD(one_way_anova)

post_hoc_Tukey

pdf("../../Plots/SupplFig_IFS_boxplots_resilienceByDistance.pdf", height = 2, width = 2.8)
print(p1)
dev.off()

pdf("../../Plots/SupplFig_IFS_boxplots_lowHighResponders_Ex1.pdf", height = 2, width = 2.8)
print(p2)
dev.off()

pdf("../../Plots/SupplFig_IFS_boxplots_lowHighResponders_Ex6.pdf", height = 2, width = 2.8)
print(p3)
dev.off()
```
