---
title: "Figure4_Transfer"
author: "Lukas von Ziegler"
date: '2022-06-01'
output: 
  html_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

required libraries

```{r, message=FALSE, warning = FALSE}
source("UnsupervisedAnalysis_Functions.R")
library(ggplot2)
library(circlize)
library(cowplot)
library(pracma)
library(circlize)
library(tidyr)
set.seed(123)
```

# Loading the data

We load the data for the unsupervised analysis object that we produced using kmeans clustering and added BSOID to

```{r}
US <- readRDS("../data/USData.rds")
```


# Figure4

## Figure 4A Classifier Performance

```{r, fig.height=2, fig.width=8}
eval_dat <- readRDS("../data/TransferEvaluation.Rds")
eval_dat <- eval_dat[grep("kmeans.25",x = names(eval_dat))]

pdat <- NULL
#calculate F1 score
for(i in names(eval_dat)){
  eval_dat[[i]]$overall$F1 <- 2 / (eval_dat[[i]]$overall$precision^-1 + eval_dat[[i]]$overall$recall^-1)
  dat <- eval_dat[[i]]$overall
  pdat <- rbind(pdat, data.frame(run = i, label = dat$label, precision = dat$precision, recall = dat$recall, F1 = dat$F1))
}
pdat <- gather(pdat,key = "key",value = "value", -run, -label)
pdat$label <- factor(pdat$label, levels = unique(as.character(sort(as.integer(pdat$label)))))
p1 <- ggplot(pdat, aes(label,value, color = key)) + 
  geom_boxplot(outlier.shape = NA) + 
  geom_point(position = position_jitterdodge(0.1)) + 
  scale_y_continuous(limits = c(0,1), breaks = seq(from = 0, to = 1, by = 0.1)) + 
  theme_bw() + 
  scale_color_manual(values = c("black","darkred","darkblue"))

print(p1)

pdf("../Plots/Figure4_A_ClassifierPerformance.pdf", height = 2, width = 8)
print(p1)
dev.off()

```

## Figure 4B Yohimbine Behavior Flow

```{r, fig.height=5, fig.width=5}
US2 <- SplitUSData(US, select = US$meta$Session == "PostYoh" & US$meta$Condition == "Control")

PlotBehaviorFlow_Delta(US2, grouping = US2$meta$Treatment == "Yohimbin", lab = "kmeans.25")

pdf("../Plots/Figure4_B_YohimbineFlow.pdf", height = 5, width = 5)
PlotBehaviorFlow_Delta(US2, grouping = US2$meta$Treatment == "Yohimbin", lab = "kmeans.25")
dev.off()

```

## Figure 4C Yohimbine transitions

```{r, fig.height=2, fig.width=3.5}
US2 <- TwoGroupAnalysis(US2, group = US2$meta$Treatment,n_bootstraps = 10)

head(US2$Results$`Saline-vs-Yohimbin`$TransitionStats$kmeans.25)

p2 <- PlotTransitions(US2,lab = "kmeans.25", from = c("1","11"), to = c("11","7"),groupby = "Treatment", cols = c("black","#AF4B08"))
print(p2)

pdf("../Plots/Figure4_C_YohimbineTransitions.pdf", height = 2, width = 3.5)
print(p2)
dev.off()
```


## Figure 4D Yohimbine linear model

```{r, fig.height=5, fig.width=2}

grp <- log1p(10*US2$meta$Dosage)
Results <- NULL
for(j in 1:25){
  for(k in 1:25){
    dat <- NULL
    for(i in US2$files){
      jname <- rownames(i$transmatrix$kmeans.25)[j]
      kname <- colnames(i$transmatrix$kmeans.25)[k]
      dat <- append(dat, i$transmatrix$kmeans.25[j,k])
    }
    if(sum(dat) > 0){
      mod <- lm(log1p(dat)~grp)
      pval <- coef(summary(mod))[,4][2]
      Results <- rbind(Results, data.frame(j = jname, k = kname, pvalue = pval))
    }
  }
}
Results$FDR <- p.adjust(Results$pvalue, method = "BY")
Results <- Results[order(Results$FDR),]
head(Results)

p3 <- PlotTransitions(US2,lab = "kmeans.25", from = c("1","11","7"), to = c("11","7","10"),groupby = "Treatment", cols = c("black","#AF4B08"))
dat <- p3$data
assign <- match(dat$name, US2$meta$filename)
dat$Dosage <- US2$meta$Dosage[assign]

p4 <- ggplot(dat, aes(log(1+10*Dosage), log(1+value))) + 
  geom_point() + 
  facet_wrap(~ transition, ncol = 1, scales = "free") + 
  theme_bw() + 
  geom_smooth(method = "lm", color = "black") + scale_x_continuous(breaks = log(1+10*dat$Dosage))
print(p4)

pdf("../Plots/Figure4_D_YohimbineTransitionsLM.pdf", height = 5, width = 2)
print(p4)
dev.off()

```


## Figure 4E Yohimbine Embedding

```{r, fig.height=2, fig.width=3}
US2 <- CalculateStabilizedTransitions(US2, group = "Treatment",control = "Saline",labels = "kmeans.25")
US2$meta$log1pDosage <- log1p(US2$meta$Dosage*10)
p5 <- Plot2DEmbedding(US2,transitionmatrices_stabilized = "kmeans.25",colorby = "Treatment",colors =  c("black","#AF4B08"),plot.sem = TRUE, method = "umap", seed = 123)
print(p5)

pdf("../Plots/Figure4_E_YohimbineEmbedding.pdf", height = 2, width = 3.2)
print(p5)
dev.off()
```

## Figure 4F Yohimbine Embedding Dosage

```{r, fig.height=2, fig.width=2.7}
p6 <- Plot2DEmbedding(US2,transitionmatrices_stabilized = "kmeans.25",colorby = "log1pDosage", method = "umap", seed = 123)
print(p6)
pdf("../Plots/Figure4_F_YohimbineEmbedding_Dosage.pdf", height = 2, width = 2.9)
print(p6)
dev.off()
```