---
title: "Figure1_BSOID"
author: "Lukas von Ziegler"
date: '2022-06-01'
output: 
  html_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

required libraries

```{r, message=FALSE, warning = FALSE}
source("UnsupervisedAnalysis_Functions.R")
library(ggplot2)
library(circlize)
library(cowplot)
library(pracma)
library(circlize)
library(tidyr)
set.seed(123)
```

# Loading the data

We load the data for the unsupervised analysis object that we produced using kmeans clustering and added BSOID to

```{r}
US <- readRDS("../data/USData.rds")
```


# Figure1

## Figure 1A CSI classical data

```{r, fig.height=3, fig.width=4}
US2 <- SplitUSData(US, select = US$meta$Session %in% c("PostCSI"))
US2 <- TwoGroupAnalysis(US2, group = US2$meta$Condition,n_bootstraps = 10)

stats <- US2$Results$`CSI-vs-Control`$Statistics$raw
pdat <- US2$Report$raw
pdat <- data.frame(filename = rownames(pdat),pdat)
pdat <- gather(pdat,key = "key",value = "value", -filename)
pdat$value[is.na(pdat$value)] <- 0
assign <- match(pdat$filename, US2$meta$filename)
pdat$Group <- US2$meta$Condition[assign]

pdat <- pdat[pdat$key %in% c("classifications.Supported.count","classifications.Unsupported.count","bodycentre.center.total.time","bodycentre.distance.moving"),]
p1 <- ggplot(pdat,aes(Group,value, color = Group)) + 
  geom_boxplot(outlier.shape = NA) + 
  scale_color_manual(values = c("black","#1C75BC")) + 
  geom_point(position = position_jitter(width = 0.15)) + 
  facet_wrap(~key, scales = "free") + 
  theme_bw()

stats[stats$name %in% c("classifications.Supported.count","classifications.Unsupported.count","bodycentre.center.total.time","bodycentre.distance.moving"),]

print(p1)

pdf("../Plots/Figure1_A_BSOID_classical.pdf", height = 3, width = 4)
print(p1)
dev.off()
```

## Figure 1B BSOID in CSI bargraphs

```{r, fig.height=2, fig.width=8}

pdat <- US2$Report$BSOID.27
pdat <- data.frame(filename = rownames(pdat),pdat)
pdat <- gather(pdat,key = "key",value = "value", -filename)
pdat$value[is.na(pdat$value)] <- 0
pdat$type <- unlist(lapply(pdat$key,FUN = function(x){strsplit(x, split = "\\.")[[1]][2]}))
pdat$Cluster <- unlist(lapply(pdat$key,FUN = function(x){strsplit(x, split = "\\.")[[1]][1]}))
pdat$Cluster <- as.integer(unlist(lapply(pdat$Cluster,FUN = function(x){strsplit(x, split = "X")[[1]][2]})))
assign <- match(pdat$filename, US2$meta$filename)
pdat$Group <- US2$meta$Condition[assign]
pdat$value <- ifelse(pdat$type == "nframes",pdat$value / 25, pdat$value)
pdat$type[pdat$type == "nframes"] <- "time"
pdat <- pdat[pdat$type == "count",]
df <- aggregate(pdat$value,by = list(pdat$Cluster, pdat$type, pdat$Group), FUN = mean)
colnames(df) <- c("Cluster","type","Group","Mean")
df$SEM <- aggregate(pdat$value,by = list(pdat$Cluster, pdat$type, pdat$Group), FUN = sd)$x / sqrt(30)


p2 <- ggplot(df, aes(x=Cluster, y=Mean, fill=Group, width = 0.75)) + 
  geom_bar(stat="identity", color="black", 
           position=position_dodge()) +
  scale_fill_manual(values = c("white","#1C75BC")) +
  geom_errorbar(aes(ymin=Mean-SEM, ymax=Mean+SEM), width=.2,
                position=position_dodge(.8)) +
  geom_point(data = pdat, aes(Cluster, value, color = Group), position = position_jitterdodge(.3), color = "black", alpha = 0.2, size = 0.3)+ 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), axis.line = element_line(colour = "black")) + 
  scale_x_continuous(breaks = c(0:31)) +
  facet_wrap(~type, ncol = 1,scales = "free")

print(p2)

US2$Results$`CSI-vs-Control`$Statistics$BSOID.27

pdf("../Plots/Figure1_B_BSOID_bar.pdf", height = 2, width = 8)
print(p2)
dev.off()
```

## Figure 1C BSOID in CSI correlation to behaviors

```{r, fig.height=1, fig.width=5}

p3 <- PlotConfusionMatrix(US2$ConfusionMatrix_norm$`BSOID.27-rear.classifier`, pointsize = 4, hclust = TRUE)

print(p3)

pdf("../Plots/Figure1_C_BSOID_cor.pdf", height =1, width = 5)
print(p3)
dev.off()
```