---
title: "RenderExampleVideos"
author: "Lukas von Ziegler"
date: '2022-09-21'
output: 
  html_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Video rendering


```{r}
source("../R/DLCAnalyzer_Functions_v4.R")
```


create example videos for kmeans.25

```{r, eval = FALSE, echo=FALSE}
ts <- readRDS("../data/Trackingobject.rds")
s2c <- read.table("../metadata/s2c_all_transfer.csv", sep = ";",header = T)
s2c <- s2c[s2c$DLCFile %in% names(ts),]

clusters <- c(1:100)

for(j in 1:nrow(s2c)){
  Tracking <- ts[[s2c[j,"DLCFile"]]]
  for(i in clusters){
    CreateExampleVideos(Tracking,"kmeans.25",i, n = 1, lag = 0, min.length = 0.5, video = paste("..\\videos\\",s2c[j,"ID"],".mp4",sep = ""), folder = "Examples", name = paste(s2c[j,"ID"],"_C",i,sep = ""))
  }
}

for(i in clusters){
  vids <- list.files("Examples/")
  get <- paste("_C",i,"_",sep = "")
  write_delim(data.frame("file",paste("'Examples\\",sample(vids[grep(get,vids)]),"'",sep = "")), "inputs.txt", col_names = F)
  system(paste("ffmpeg -f concat -safe 0 -i inputs.txt -vcodec copy -acodec copy C",i,".mp4", sep = ""))
}


```